[shortcut]

[autolabel."S-waiting-on-review"]
new_pr = true

[no-merges]
# PRs with the following labels will be skipped 
exclude_titles = ["exclude me"]
# Add the following labels to PRs with merge commits
labels = ["has-merge-commits", "S-waiting-on-author"]
# Post the following warning message as a comment on PRs with merge commits
message = """
Hi! This repository does not allow merge commits.
Your PR cannot be merged until it is rebased.
"""

[relabel]
allow-unauthenticated = [
    "*",
]


[github-releases]
format = "rustc"
project-name = "Rust"
changelog-path = "RELEASES.md"
changelog-branch = "main"

[autolabel."foo"]
trigger_files = ["foo"]

[mentions."foo"]
cc = ["@grashgal"]

[assign]
contributing_url = "https://rust-lang.github.io/cargo/contrib/"
warn_non_default_branch = true

[assign.owners]
"/" = ["@ehuss"]
"/foo" = ["@grashgal"]
