[shortcut]
[relabel]
allow-unauthenticated = ["*"]

[mentions.'README.md']
cc = ["@ehuss"]

[mentions.'example1']

[mentions.'example2']
message = "This is a message."

[autolabel."bar"]
trigger_labels = ["foo"]

[autolabel."foo"]
new_pr = true

[assign]
non_default_branch = true
contributing_url = "https://rustc-dev-guide.rust-lang.org/contributing.html"

[assign.groups]
"group1" = ["@ehuss"]
"group2" = ["group1", "@octocat"]
"group3" = ["@EHUSS"]
group4 = ["@grashgal"]
recursive1a = ["recursive1b"]
recursive1b = ["recursive1a"]

recursive2a = ["recursive2b"]
recursive2b = ["recursive2a", "octocat"]
# fallback = ["grashgal"]

[assign.owners]
# "**" = ["@ehuss"]
# "README.md" = ["@octocat"]
"/foo" = ["@ghost"]
"/bar" = ["group2"]
"/only" = ["group1"]
"/grash" = ["grashgal"]
