[merge-conflicts]
remove = ['S-waiting-on-bors', 'bar']
add = ['S-waiting-on-author']
unless = ['S-blocked', 'S-waiting-on-crater', 'S-waiting-on-team', 'S-waiting-on-review']

[review-submitted]
# This label is added when a "request changes" review is submitted.
reviewed_label = "S-waiting-on-author"
# These labels are removed when a "request changes" review is submitted.
review_labels = ["S-waiting-on-review"]

[review-requested]
# Those labels are removed when PR author requests a review from an assignee
remove_labels = ["S-waiting-on-author"]
# Those labels are added when PR author requests a review from an assignee
add_labels = ["S-waiting-on-review"]

[assign]
warn_non_default_branch.enable = true

[[assign.warn_non_default_branch.exceptions]]
title = "[beta"
branch = "beta"

[[assign.warn_non_default_branch.exceptions]]
title = "[stable"
branch = "stable"

[assign.owners]
"*" = ["@ehuss", "@grashgal"]

[relabel]
allow-unauthenticated = ["*"]
